name: python-ci
on:
  push:
    paths:
      - '**/*.py'
      - 'requirements.txt'
      - '.github/workflows/python-ci.yml'
  pull_request:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'
      - name: Install deps
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
      - name: Tests
        run: |
          python -m pytest -q || python -m unittest -q
